title: "Mark's Blog"
author: "Mark P."
description: "My personal blog about computer science."
permalink: /:year/:month/:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

sidebar: true               
show_excerpts: true        
show_related: true          
show_description: false     
show_title: true           
show_frame: true

# Menu

icons:
  - {icon: moon}
  - {icon: sun}

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {icon: home, file: "index.html"}
  - {icon: info, file: "about.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Credits, icon: heart,  file: "credits.md"}
  - {title: Mail, icon: envelope, url: "mailto:markminpeng@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/MarkMP1/blog.markp.xyz"}
  - {title: RSS Feed, icon: rss, url: "/feed.xml"}
comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
